version: '3.7'

services: 
  client:
    container_name: dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development